name: Preview Deploy

on:
  push:
    branches: [content-preview]

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    name: Build & Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 8.15.0
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate
        run: pnpm run validate:cms && pnpm run validate:i18n

      - name: Build
        run: pnpm run build
        env:
          ENVIRONMENT: preview

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy dist --project-name=astro-sveltia-cloudflare --branch=content-preview